version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - frontend
    networks:
      - copybase

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - copybase

networks:
  copybase:
    driver: bridge
